import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { Providers } from "@/providers";
import { backgroundColor } from "@/constants";
import { css } from "@emotion/react";
import { GlobalEmotion } from "@/components/GlobalEmotion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalEmotion />
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
